import type { ParticipantGroup } from "../types/participant.types";

export const participantGroupMock: ParticipantGroup = {
  groupName: "2026 SW 동아리 MT",
  participants: [
    {
      id: "1",
      name: "이서연",
      department: "컴퓨터공학과",
      initials: "이",
      visibility: "public",
      role: "general",
      color: "#625DF5",
    },
    {
      id: "2",
      name: "박지호",
      department: "전기공학과",
      initials: "박",
      visibility: "private",
      role: "general",
      color: "#8B5CF6",
    },
    {
      id: "3",
      name: "최수아",
      department: "산업디자인",
      initials: "최",
      visibility: "public",
      role: "staff",
      color: "#71717A",
    },
    {
      id: "4",
      name: "정다은",
      department: "경영학과",
      initials: "정",
      visibility: "private",
      role: "general",
      color: "#F59E0B",
    },
    {
      id: "5",
      name: "한지우",
      department: "전자공학과",
      initials: "한",
      visibility: "public",
      role: "general",
      color: "#EC4899",
    },
    {
      id: "6",
      name: "오승현",
      department: "기계공학과",
      initials: "오",
      visibility: "public",
      role: "staff",
      color: "#14B8A6",
    },
    {
      id: "7",
      name: "강민서",
      department: "심리학과",
      initials: "강",
      visibility: "private",
      role: "general",
      color: "#A78BFA",
    },
    {
      id: "8",
      name: "윤재원",
      department: "수학과",
      initials: "윤",
      visibility: "public",
      role: "general",
      color: "#F97316",
    },
    {
      id: "9",
      name: "신예린",
      department: "영문학과",
      initials: "신",
      visibility: "private",
      role: "staff",
      color: "#64748B",
    },
    {
      id: "10",
      name: "조현준",
      department: "화학공학과",
      initials: "조",
      visibility: "public",
      role: "general",
      color: "#22C55E",
    },
    {
      id: "11",
      name: "임수진",
      department: "건축학과",
      initials: "임",
      visibility: "public",
      role: "general",
      color: "#D946EF",
    },
    {
      id: "12",
      name: "김도윤",
      department: "체육교육과",
      initials: "김",
      visibility: "private",
      role: "general",
      color: "#06B6D4",
    },
  ],
};

export function getParticipantListMock() {
  return participantGroupMock;
}
